name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Add GitHub NuGet source
        run: |
          dotnet nuget add source \
            --username rasalshukla \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text \
            --name github \
            https://nuget.pkg.github.com/rasalshukla/index.json

      - name: Restore dependencies
        run: dotnet restore
        working-directory: MyLibrary

      - name: Build
        run: dotnet build -c Release
        working-directory: MyLibrary

      - name: Pack NuGet package
        run: dotnet pack -c Release --no-build -o out
        working-directory: MyLibrary

      - name: Push package to GitHub Packages
        run: |
          dotnet nuget push out/*.nupkg \
            --source "https://nuget.pkg.github.com/rasalshukla/index.json" \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --skip-duplicate
        working-directory: MyLibrary
