name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: MyLibrary

      - name: Build project
        run: dotnet build -c Release
        working-directory: MyLibrary

      - name: Pack NuGet package
        run: dotnet pack -c Release --no-build -o out
        working-directory: MyLibrary

      - name: Add GitHub Package Source
        run: |
          dotnet nuget remove source github || true
          dotnet nuget add source \
            --name github \
            --username ${{ github.actor }} \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text \
            https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

      - name: Push NuGet package to GitHub Packages
        run: |
          dotnet nuget push out/*.nupkg \
            --source github \
            --skip-duplicate
        working-directory: MyLibrary
