name: Publish NuGet Package

on:
  push:
    tags: ['v*']

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Debug: List repository root
        run: ls -R .

      - name: Restore & Build
        run: |
          cd MyLibrary
          dotnet restore
          dotnet build -c Release

      - name: Debug: List build output
        run: |
          cd MyLibrary
          ls -R bin

      - name: Pack NuGet package
        run: |
          cd MyLibrary
          dotnet pack -c Release -o ../out

      - name: Debug: List packaged files
        run: ls -R out

      - name: Push NuGet package
        run: |
          dotnet nuget push out/*.nupkg \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key "${{ secrets.GITHUB_TOKEN }}" \
            --skip-duplicate
