name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          source-url: https://nuget.pkg.github.com/rasalshukla/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore dependencies
        run: dotnet restore
        working-directory: MyLibrary

      - name: Build
        run: dotnet build -c Release
        working-directory: MyLibrary

      - name: Pack NuGet package
        run: dotnet pack -c Release --no-build -o out
        working-directory: MyLibrary

      - name: Publish to GitHub Packages
        run: dotnet nuget push out/*.nupkg --source "github" --skip-duplicate
        working-directory: MyLibrary
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
