name: Publish NuGet Package

on:
  push:
    tags: ['v*']

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # or '6.0.x' if targeting net6.0

    - name: Build & Pack Library
      run: |
        cd MyLibrary
        dotnet restore
        dotnet build -c Release
        dotnet pack -c Release -o ../out

    - name: Publish to GitHub Packages
      run: |
        dotnet nuget push ../out/*.nupkg \
          --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
          --api-key ${{ secrets.GITHUB_TOKEN }} \
          --skip-duplicate
      working-directory: MyLibrary
