name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Create empty nuget.config
        run: |
          echo '<?xml version="1.0" encoding="utf-8"?>' > empty-nuget.config
          echo '<configuration><packageSources></packageSources></configuration>' >> empty-nuget.config

      - name: Restore dependencies
        run: dotnet restore
        working-directory: MyLibrary

      - name: Build project
        run: dotnet build -c Release
        working-directory: MyLibrary

      - name: Pack NuGet package
        run: dotnet pack -c Release --no-build -o out
        working-directory: MyLibrary

      - name: Push NuGet package to GitHub Packages
        run: |
          echo "Listing .nupkg files in 'out' folder:"
          ls -lh MyLibrary/out

          echo "Pushing to GitHub Packages..."
          dotnet nuget push MyLibrary/out/*.nupkg \
            --source "https://nuget.pkg.github.com/Inter-IKEA-Digital/index.json" \
            --api-key "${{ secrets.GITHUB_TOKEN }}" \
            --configfile ./empty-nuget.config \
            --skip-duplicate
