name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build & Pack MyLibrary
        run: |
          dotnet restore MyLibrary
          dotnet build MyLibrary -c Release
          dotnet pack MyLibrary -c Release -o out

      - name: Publish NuGet Package to GitHub
        run: |
          dotnet nuget push out/*.nupkg \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --skip-duplicate
