name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

permissions:
  packages: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore
        working-directory: MyLibrary

      - name: Build
        run: dotnet build -c Release
        working-directory: MyLibrary

      - name: Pack
        run: dotnet pack -c Release --no-build -o out
        working-directory: MyLibrary

      - name: Push package to GitHub Packages
        run: |
          dotnet nuget push out/*.nupkg \
            --source "https://nuget.pkg.github.com/rasalshukla/index.json" \
            --api-key "${{ secrets.GITHUB_TOKEN }}" \
            --skip-duplicate
        working-directory: MyLibrary
